export const CLAUDE_STARTUPS_STATUS = "As of 2026-10-09, the Team and $1,000 API credit offers are over capacity. All applications will be re-reviewed.";

export interface DatedTerms {
  text: string;
  url: string;
  readOn: string;
}

export interface StartupProgram {
  name: string;
  slug: string;
  category: "cloud-infrastructure" | "fintech-banking" | "developer-tools" | "ai-tools";
  creditValue: string;
  eligibility: string;
  duration?: string;
  applicationDifficulty: "open" | "accelerator-only" | "invite-only" | "vc-backed" | "vc-referral";
  whatsIncluded: string;
  hiddenConstraints?: string;
  vestingSchedule?: string;
  status?: string;
  programmePage?: string;
  whenCreditsRunOut?: DatedTerms;
  governedByConditionsOf?: string;
}

export const STARTUP_PROGRAMS: readonly StartupProgram[] = [
  { name: "AWS Activate", slug: "aws-activate", category: "cloud-infrastructure", creditValue: "$1K–$5K (Founders), up to $200K (Portfolio)", eligibility: "Pre-Series B, founded in the last 10 years, AWS account on a paid plan. Founders: self-funded. Portfolio: needs an Activate Provider Org ID.", duration: "Activate credits expire on a date shown in the AWS Billing console.", applicationDifficulty: "open", whatsIncluded: "AWS credits, which can also pay for AWS Support. Technical guidance, mentoring and go-to-market resources.", hiddenConstraints: "Founders start at $1,000; select participants may get up to $5,000. Portfolio needs an Org ID from an Activate Provider such as an accelerator or VC firm. AWS cannot extend expiry dates, even with credits unused. Accounts on the Free plan are not eligible.", vestingSchedule: "One award per approved application; a later, larger award pays only the difference", whenCreditsRunOut: { text: "Your AWS account is billed for usage beyond the credits. Some services are not eligible for the credits.", url: "https://aws.amazon.com/awscredits/", readOn: "2026-10-08" } },
  { name: "Google Cloud for Startups", slug: "google-cloud-for-startups", category: "cloud-infrastructure", creditValue: "$2K (Start), up to $200K (Scale), up to $350K (Scale AI)", eligibility: "Start: no funding yet but plans to raise venture funding soon, founded within 24 months, working MVP; Scale: VC funding from pre-seed to Series A (Series A within the last 12 months; angel money does not count), founded within 5 years.", duration: "12 months (Start), 2 years (Scale)", applicationDifficulty: "open", whatsIncluded: "Google Cloud and Firebase credits, 12 months of Google Workspace Business Plus, technical training and business support. The AI tier adds $150K of credits.", hiddenConstraints: "Equity funding required \u2014 bootstrapped startups don\u2019t qualify for Scale tier. $200K is split $100K/year. Must use within Google Cloud (not transferable). 24-month expiry. Requires application review.", vestingSchedule: "Scale: year 1 covers usage up to $100K ($250K for AI); year 2 covers 20% of spend, up to $100K more", whenCreditsRunOut: { text: "Usage beyond the credits is billed to you. Google is not required to notify you when the credits are exhausted.", url: "https://cloud.google.com/terms/startup-program-tos", readOn: "2026-10-08" } },
  { name: "Microsoft for Startups (formerly Founders Hub)", slug: "microsoft-founders-hub", category: "cloud-infrastructure", creditValue: "$200 on sign-up; up to $150K as Azure usage grows or with an Investor Network partner", eligibility: "B2B software, AI or tech startups, pre-seed to Series C, privately held; no investor needed. Business verification and sustained Azure usage unlock more credits, and Investor Network backing starts most startups at $100K.", duration: "Activate within 90 days; the first $200 lasts 90 days, the verification credit 180 days, and credits from the $25K milestone up to 2 years", applicationDifficulty: "open", whatsIncluded: "Azure credits and Azure AI models. GitHub Enterprise, Microsoft 365 Business Premium, Visual Studio Enterprise and LinkedIn Premium offers are for Investor Network-backed startups only.", hiddenConstraints: "Basic path gives only $5K without investor connection. Premium path up to $150K requires investor network verification. Credits expire in 12 months. Azure-only (not applicable to M365 or other Microsoft products).", vestingSchedule: "Released in milestones as you verify the business and use more Azure", whenCreditsRunOut: { text: "When the credits are used up or reach their end date, the subscription converts automatically to Pay-As-You-Go and you pay for further usage.", url: "https://azure.microsoft.com/en-us/pricing/offers/ms-azr-0036p", readOn: "2026-10-08" } },
  { name: "DigitalOcean Startups", slug: "digitalocean-hatch", category: "cloud-infrastructure", creditValue: "Credits for 12 months; amount varies, up to $10,000 a month", eligibility: "Raised $10M or less; apply through a partner or directly", duration: "12 months", applicationDifficulty: "open", whatsIncluded: "Compute credits for most DigitalOcean services, 15 months of free Standard-tier support; GPU credits are a separate benefit for selected startups", hiddenConstraints: "Credits exclude GPU Droplets, H100 GPU products, inference, third-party AI models, Paperspace and Cloudways. Use over $10,000 in a month is charged. Only for startups that have not used DigitalOcean credits before.", vestingSchedule: "Lump sum per partner agreement", governedByConditionsOf: "digitalocean" },
  { name: "Cloudflare Startup Program", slug: "cloudflare-startup-program", category: "cloud-infrastructure", creditValue: "$10K, $100K or $350K by tier", eligibility: "Tier 3 ($10K): bootstrapped or self-funded, under $1M raised; Tiers 2 ($100K) and 1 ($350K): funded by an affiliated partner, Tier 1 with $5M+ raised.", duration: "1 year or until used up", applicationDifficulty: "open", whatsIncluded: "Credits for usage-based services such as Workers and R2 (R2 up to $10K; Workers AI up to $2.5K, $10K or $50K by tier). AI Gateway is not covered. Core security and networking features are free at every tier.", hiddenConstraints: "Tier is based on funding stage \u2014 bootstrapped startups get only $5K. Higher tiers require more funding documentation. Credits are Cloudflare-only. Limited time window to use credits.", vestingSchedule: "Lump sum per tier" },
  { name: "Stripe Atlas", slug: "stripe-atlas", category: "fintech-banking", creditValue: "Over $50K in partner discounts, plus $2.5K of Stripe credits", eligibility: "Companies incorporated through Atlas ($500, then $100 a year after the first year)", duration: "Varies by perk; Stripe credits last the first year", applicationDifficulty: "open", whatsIncluded: "$2.5K of Stripe product credits for the first year, $5K of AWS Activate credits (new AWS users), $100K of Cloudflare credits through the Cloudflare Startup Program, Microsoft for Startups Azure credits, a 30-minute immigration attorney consult (Ellis), and banking through Stripe Treasury.", hiddenConstraints: "Requires Stripe Atlas incorporation ($500 one-time fee). Perks are from third parties \u2014 each has own eligibility requirements. Processing credits only apply to Stripe payments. Some perks expire 90 days after incorporation.", vestingSchedule: "Available once the Atlas application is approved" },
  { name: "Brex Partner Perks", slug: "brex-partner-perks", category: "fintech-banking", creditValue: "Over $350K in partner discounts and credits", eligibility: "Brex customers", duration: "Varies by partner", applicationDifficulty: "open", whatsIncluded: "Up to $5K of AWS credits for new Brex customers (subject to Activate eligibility), $1K of OpenAI credits for a year, up to $200K of Google Cloud and Firebase credits over 2 years, 6 months of Notion Plus, 30% off Slack for 12 months.", hiddenConstraints: "Must be a Brex cardholder. Individual perks have separate eligibility and expiry. Some require minimum card spend. Google Cloud $200K requires separate Google for Startups qualification. Partner perks change frequently.", vestingSchedule: "Per-partner activation" },
  { name: "Mercury Perks", slug: "mercury-perks", category: "fintech-banking", creditValue: "Banking perks bundle", eligibility: "Mercury banking customers", duration: "Varies by perk", applicationDifficulty: "open", whatsIncluded: "1 year of Datadog free (up to $100K in credits; Series A or earlier, new Datadog customers), up to $5K of AWS Activate credits, 50% off QuickBooks Online for 3 months. Mercury's Google Cloud offer is paused.", hiddenConstraints: "Must have Mercury business account. Datadog credit is usage-based cap \u2014 may not reach full $100K value. Google Cloud credits require separate application to Google for Startups. Perks are subject to partner availability.", vestingSchedule: "Per-partner activation" },
  { name: "Ramp Partner Rewards", slug: "ramp-partner-rewards", category: "fintech-banking", creditValue: "Over $350K in partner rewards", eligibility: "Ramp customers", duration: "Varies", applicationDifficulty: "open", whatsIncluded: "AWS credits through AWS Activate and OpenAI API credits (Ramp states no amount for either), $350 of Google Cloud credits, 6 months of Notion Business with Notion AI.", hiddenConstraints: "Must be Ramp cardholder. AWS credits are a subset of what AWS Activate offers separately. Partner perks overlap with Brex offerings. Some discounts require annual commitments.", vestingSchedule: "Per-partner activation" },
  { name: "SVB Startup Banking Offers", slug: "svb-startup-banking-offers", category: "fintech-banking", creditValue: "$5K AWS + partner offers", eligibility: "SVB clients (SVB is a division of First Citizens Bank)", duration: "Varies", applicationDifficulty: "open", whatsIncluded: "$5K of AWS Activate credits (with an Activate Provider Org ID, pre-Series B), $5K of MongoDB credits for 12 months, 25% off Slack upgrades (up to $9K). 79 offers from 58 vendors; no Google Cloud offer.", hiddenConstraints: "SVB was acquired by First Citizens Bank (2023) \u2014 program continuity uncertain for new applicants. Google Cloud credits are usage-based annual cap (not guaranteed full amount). Partner perks change over time.", vestingSchedule: "Per-partner activation" },
  { name: "PostHog for Startups", slug: "posthog-yc-deal", category: "developer-tools", creditValue: "$50K in credits (YC: $50K a year)", eligibility: "Under 2 years old and under $5M raised. YC companies under $25M raised get $50K a year instead.", duration: "12 months (YC: renews yearly while eligible)", applicationDifficulty: "open", whatsIncluded: "Credits for product analytics, session replay, feature flags and experiments, plus about $12K of partner perks. Since 2026-09-14, credits don't cover PostHog AI, Desktop, the Slack app, Replay Vision or Inbox.", hiddenConstraints: "YC companies only \u2014 not open to general startups. $25M fundraising cap. Must maintain active YC alumni status. Covers PostHog only \u2014 not transferable.", vestingSchedule: "Credits for 12 months; the YC deal renews yearly" },
  { name: "Claude Startups (Anthropic)", slug: "claude-startups", category: "ai-tools", creditValue: "Up to $7,000 in Claude products and credits. Includes a free year of Claude Team and a $1,000 API credit.", eligibility: "Founded in the last five years or funded in the last two. VC funding is not required.", applicationDifficulty: "open", whatsIncluded: "One year of Claude Team with up to five Premium seats, a one-time $1,000 API credit, and third-party offers worth up to $45,000. Partner VCs may add up to $100K. Credits apply to the first-party Claude API only.", status: CLAUDE_STARTUPS_STATUS, programmePage: "https://claude.com/programs/startups" },
  { name: "OpenAI for Startups", slug: "openai-for-startups", category: "ai-tools", creditValue: "Credit value not stated.", eligibility: "Requires a referral code from a partner VC.", applicationDifficulty: "vc-referral", whatsIncluded: "Credits only through a partner VC. The application needs the VC's referral code. No credit amount stated. Brex and Ramp customer perks on this page include OpenAI credits without VC backing.", programmePage: "https://openai.com/business/why-openai/startups/" },
  { name: "Amazon Kiro (AWS Startups)", slug: "amazon-kiro-aws-startups", category: "ai-tools", creditValue: "Up to 1 year of Kiro Pro+ ($40 per user a month)", eligibility: "Early stage to Series A, without active AWS Activate credits; Kiro's startup page asks for VC backing and its terms do not; not available in France, Germany, Italy, Spain, Poland, Brazil, Mexico, Argentina, the UAE, China or sanctioned regions; apply by 2026-12-31.", duration: "Credits expire 1 year after they are issued", applicationDifficulty: "open", whatsIncluded: "Kiro Pro+ for up to 2, 10 or 30 users (Starter, Growth and Scale tiers).", hiddenConstraints: "Requires existing AWS Startups membership (not standalone). Pro+ credit allocation is model-dependent (Sonnet 4 costs 1.3x). Free tier duration is exactly 12 months. Not combinable with other Kiro promotions.", vestingSchedule: "Deposited once to your AWS account" },
  { name: "Amplitude Early Stage Startup Pricing", slug: "amplitude-startup-scholarship", category: "ai-tools", creditValue: "1 year of the Growth plan free", eligibility: "Under 20 employees and under $10M raised", duration: "1 year; year 2 at 40% off the annual Plus plan, or move to the free plan", applicationDifficulty: "open", whatsIncluded: "The full Growth plan for 200K monthly tracked users or 100M events a month.", hiddenConstraints: "Growth plan converts to paid ($49+/mo) after 1 year. Application review required. MTU/event limits are soft \u2014 overage may be billed. Plan features may change during the free year.", vestingSchedule: "Full plan for 12 months" },
];

export const STARTUP_CREDITS_META_DESCRIPTION = `Compare ${STARTUP_PROGRAMS.length} startup programs: AWS Activate, Google for Startups, Microsoft for Startups, Cloudflare, DigitalOcean Startups, Stripe Atlas, Brex, Mercury, and more. Credit values, eligibility, vesting, and stacking strategies. [[freshness]]`;
